perf(taos-optin): optimizing tmq poll
taosdata/taos-connector-rust pull request #375
Opened 2024-11-06 13:49 UTC by qevolg

Optimizing tmq poll

2024-11-08 03:39 UTC, sheyanjie-qq commented on taos-optin/src/tmq/raw.rs
> +                        let res = unsafe { (tmq.tmq_consumer_poll)(ptr, timeout) };
ptr is consumer?

2024-11-08 03:42 UTC, sheyanjie-qq commented on taos-optin/src/tmq/raw.rs
> +                            tracing::warn!("Send res failed, cache res: {res:?}");
warn -> debug

2024-11-08 03:47 UTC, sheyanjie-qq commented on taos-optin/src/tmq/mod.rs
> +                            table_name,
check data

2024-11-08 07:22 UTC, sheyanjie-qq approved these changes

2024-11-10 10:39 UTC, zitsen requested changes

2024-11-10 10:39 UTC, zitsen commented on taos-optin/src/tmq/raw.rs
> +                    while let Some(sender) = receiver.recv().await {
Only receiver.recv() is async method here, please use blocking method instead, such as flume::Receiver::recv()

2024-11-12 05:35 UTC, sheyanjie-qq approved these changes

2024-11-12 05:55 UTC, zitsen approved these changes

2024-11-19 06:34 UTC, merged